name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux
            runner: ubuntu-latest
          - target: apk
            runner: ubuntu-latest
          - target: windows
            runner: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ${{ matrix.target }}
        id: build
        uses: flet-dev/flet-build-action@v1
        with:
          target: ${{ matrix.target }}
          runner-python-version: "3.12"  # Te recomiendo 3.12, ya que 3.14 aún está en fase de pruebas
          bundled-python-version: "3.12"
          build-number: ${{ github.run_number }}

      - name: Upload build archive
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.target }} # Le damos un nombre único a cada archivo subido
          path: ${{ steps.build.outputs.archive-path }}
          if-no-files-found: error
